### ISSUE TITLE
python 3.12 pytests fail

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/PyGenePlexus#340]
The pytests fail for the following reason but the code seems to work fine

`Run tox
python3.12: install_deps> python -I -m pip install -r /home/runner/work/PyGenePlexus/PyGenePlexus/requirements-dev.txt -r /home/runner/work/PyGenePlexus/PyGenePlexus/requirements.txt
ERROR: Exception:
Traceback (most recent call last):
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 187, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in __init__
    super().__init__(
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 159, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 236, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 315, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 701, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/home/runner/work/PyGenePlexus/PyGenePlexus/.tox/python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/tmp/pip-build-env-5cvifdfh/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'

Collecting tox==4.23.2 (from -r /home/runner/work/PyGenePlexus/PyGenePlexus/requirements-dev.txt (line 1))
  Using cached tox-4.23.2-py3-none-any.whl.metadata (3.7 kB)
Collecting pytest==7.4.2 (from -r /home/runner/work/PyGenePlexus/PyGenePlexus/requirements-dev.txt (line 2))
  Downloading pytest-7.4.2-py3-none-any.whl.metadata (7.9 kB)
Collecting pytest-cov==4.1.0 (from -r /home/runner/work/PyGenePlexus/PyGenePlexus/requirements-dev.txt (line 3))
  Downloading pytest_cov-4.1.0-py3-none-any.whl.metadata (26 kB)
Collecting pytest-order==1.1.0 (from -r /home/runner/work/PyGenePlexus/PyGenePlexus/requirements-dev.txt (line 4))
  Downloading pytest_order-1.1.0-py3-none-any.whl.metadata (7.5 kB)
Collecting parameterized==0.9.0 (from -r /home/runner/work/PyGenePlexus/PyGenePlexus/requirements-dev.txt (line 5))
  Downloading parameterized-0.9.0-py2.py3-none-any.whl.metadata (18 kB)
Collecting requests-mock==1.11.0 (from -r /home/runner/work/PyGenePlexus/PyGenePlexus/requirements-dev.txt (line 6))
  Downloading requests_mock-1.11.0-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting pytest-mock==3.11.1 (from -r /home/runner/work/PyGenePlexus/PyGenePlexus/requirements-dev.txt (line 7))
  Downloading pytest_mock-3.11.1-py3-none-any.whl.metadata (3.8 kB)
Collecting setuptools==75.5.0 (from -r /home/runner/work/PyGenePlexus/PyGenePlexus/requirements-dev.txt (line 8))
  Using cached setuptools-75.5.0-py3-none-any.whl.metadata (6.8 kB)
Collecting numpy==1.23.5 (from -r /home/runner/work/PyGenePlexus/PyGenePlexus/requirements.txt (line 1))
  Downloading numpy-1.23.5.tar.gz (10.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 126.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
python3.12: exit 2 (5.39 seconds) /home/runner/work/PyGenePlexus/PyGenePlexus> python -I -m pip install -r /home/runner/work/PyGenePlexus/PyGenePlexus/requirements-dev.txt -r /home/runner/work/PyGenePlexus/PyGenePlexus/requirements.txt pid=1822
  python3.12: FAIL code 2 (5.58 seconds)
  evaluation failed :( (5.66 seconds)

Error: Process completed with exit code 2.`

**Comment by ChristopherMancuso** [comment]
this was fixed with #364
